### ISSUE TITLE
Cannot install dolo in julia 1.1

### ISSUE THREAD

**Issue by yordiak** [EconForge/Dolo.jl#148]
when i try to install dolo in julia 1.1. i receive the following message

> ERROR: Unsatisfiable requirements detected for package Dolo [9d24351c]:
>  Dolo [9d24351c] log:
>  ├─possible versions are: [0.1.0, 0.2.0, 0.3.0-0.3.1] or uninstalled
>  ├─restricted to versions * by an explicit requirement, leaving only versions [0.1.0, 0.2.0, 0.3.0-0.3.1]
>  └─restricted by julia compatibility requirements to versions: uninstalled — no versions left

how to solve this issue? 

also, i would like to ask if this project is still active

**Comment by sglyon** [comment]
I think what happened was that we need to signal that we are compatible with Julia version >= 0.7

@albop I think we were either at or very close to a release that works on Julia 1.0. Do you know if we are ready for that? If we are, let's push the release button to fix this problem.

Thanks

**Comment by sglyon** [comment]
It looks like tests are passing on 1.0, so I'm going to go ahead and tag. IF there are other changes we want in a release, we can make another one quickly.

**Comment by albop** [comment]
Yes I completed the tests for 1.0 but never tried 1.1. Also 0.7 wasn't
working due to some package requirement.

Le sam. 2 mars 2019 à 22:27, Spencer Lyon <notifications@github.com> a
écrit :

**Comment by albop** [comment]
@sglyon : Any chance you can push the release button? I'm on holiday for
the week. (We need to check the state of Dolang too)

Le sam. 2 mars 2019 à 22:25, Spencer Lyon <notifications@github.com> a
écrit :

**Comment by albop** [comment]
Update : I tagged v0.3.0 for Dolang which is >=1.0

**Comment by yordiak** [comment]
installation issue is fixed, so i am closing this thread

**Comment by albop** [comment]
hmm, @yordiak, how did you do the install ? did you use `dev Dolo` ? (which works) or `add Dolo` ? (which afaik is still broken)

**Comment by yordiak** [comment]
i used `add Dolo`. it worked on my machine (win10 64bit)

**Comment by albop** [comment]
my bad, it is not broken, I did the last fix 30 min ago, and didn't expect the julia publishers to pick up the fix so quickly.
@yordiak : As for your original question: project is well alive, but has a high seasonal component. It is also considered a research project until version 0.5 which will occur some day. Any feedback is welcome.
@sglyon : thank you for stepping in
